# Generated by Django 4.0.5 on 2025-10-14 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=10, unique=True)),
                ('index', models.CharField(blank=True, max_length=2)),
                ('road', models.ForeignKey(db_column='road', on_delete=django.db.models.deletion.CASCADE, to='all_roads.road')),
            ],
        ),
    ]
