# Generated by Django 4.0.5 on 2025-10-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0003_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='end_lat',
            field=models.DecimalField(decimal_places=16, default=0.0, max_digits=32),
        ),
        migrations.AddField(
            model_name='segment',
            name='end_lon',
            field=models.DecimalField(decimal_places=16, default=0.0, max_digits=32),
        ),
        migrations.AddField(
            model_name='segment',
            name='start_lat',
            field=models.DecimalField(decimal_places=16, default=0.0, max_digits=32),
        ),
        migrations.AddField(
            model_name='segment',
            name='start_lon',
            field=models.DecimalField(decimal_places=16, default=0.0, max_digits=32),
        ),
    ]
