# Generated by Django 4.0.5 on 2025-10-14 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0004_segment_end_lat_segment_end_lon_segment_start_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='end_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='end_point', to='all_roads.address'),
        ),
        migrations.AddField(
            model_name='segment',
            name='error_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='segment',
            name='start_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='start_point', to='all_roads.address'),
        ),
    ]
