# Generated by Django 4.0.5 on 2025-10-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0005_segment_end_point_segment_error_processing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='status',
            field=models.CharField(choices=[('666699', 'No response'), ('FF0000', 'Werser (<40 km/h)'), ('FF5050', 'Bad (<50 km/h)'), ('FF9966', 'Poor (<60 km/h)'), ('FFFFCC', 'Manageable (<70 km/h)'), ('00CC00', 'OK (<80 km/h)'), ('339933', 'Good (<90 km/h)'), ('006600', 'Better (>=90 km/h)')], default='666699', help_text='Traffic color code based on average speed', max_length=6),
        ),
    ]
