# Generated by Django 4.0.5 on 2025-10-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0006_alter_segment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='end_lat',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='segment',
            name='end_lon',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='segment',
            name='start_lat',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='segment',
            name='start_lon',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9),
        ),
    ]
