# Generated by Django 4.0.5 on 2025-10-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0007_alter_segment_end_lat_alter_segment_end_lon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lat',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='address',
            name='lng',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9),
        ),
    ]
