# Generated by Django 4.0.5 on 2025-11-13 03:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0008_alter_address_lat_alter_address_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=16, unique=True)),
                ('position', models.PositiveSmallIntegerField(help_text='Order of this sub-segment within its parent segment (1–25).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)])),
                ('start_lat', models.DecimalField(decimal_places=5, default=0.0, max_digits=9)),
                ('start_lon', models.DecimalField(decimal_places=5, default=0.0, max_digits=9)),
                ('end_lat', models.DecimalField(decimal_places=5, default=0.0, max_digits=9)),
                ('end_lon', models.DecimalField(decimal_places=5, default=0.0, max_digits=9)),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('travel_time', models.IntegerField(default=0)),
                ('avg_speed', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('error_processing', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('666699', 'No response'), ('FF0000', 'Werser (<40 km/h)'), ('FF5050', 'Bad (<50 km/h)'), ('FF9966', 'Poor (<60 km/h)'), ('FFFFCC', 'Manageable (<70 km/h)'), ('00CC00', 'OK (<80 km/h)'), ('339933', 'Good (<90 km/h)'), ('006600', 'Better (>=90 km/h)')], default='666699', help_text='Traffic color code based on average speed', max_length=6)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsegments', to='all_roads.segment')),
            ],
            options={
                'verbose_name': 'Sub-segment',
                'verbose_name_plural': 'Sub-segments',
                'db_table': 'sub_segments',
                'ordering': ['segment_id', 'position'],
            },
        ),
        migrations.AddConstraint(
            model_name='subsegment',
            constraint=models.UniqueConstraint(fields=('segment', 'position'), name='uq_subsegment_segment_position'),
        ),
        migrations.AddConstraint(
            model_name='subsegment',
            constraint=models.CheckConstraint(check=models.Q(('position__gte', 1), ('position__lte', 25)), name='ck_subsegment_position_1_25'),
        ),
    ]
