# Generated by Django 4.0.5 on 2025-11-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0009_subsegment_subsegment_uq_subsegment_segment_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsegment',
            name='end_lat',
            field=models.DecimalField(decimal_places=16, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='subsegment',
            name='end_lon',
            field=models.DecimalField(decimal_places=16, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='subsegment',
            name='start_lat',
            field=models.DecimalField(decimal_places=16, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='subsegment',
            name='start_lon',
            field=models.DecimalField(decimal_places=16, default=0.0, max_digits=18),
        ),
    ]
