# Generated by Django 4.0.5 on 2026-02-22 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0010_alter_subsegment_end_lat_alter_subsegment_end_lon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootCauseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=32)),
                ('description', models.CharField(choices=[('pavement', 'Pavement'), ('shoulders', 'Shoulders'), ('drainage', 'Drainage'), ('traffic_volume', 'Traffic Volume'), ('bridges', 'Bridges'), ('culverts', 'Culverts'), ('road_junctions', 'Road Junctions'), ('others', 'Others')], max_length=32)),
                ('subsegment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_cause_analyses', to='all_roads.subsegment')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RootCauseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natural_feature', models.CharField(choices=[('subgrade_properties', 'Subgrade Properties'), ('vegetation', 'Vegetation'), ('topography', 'Topography'), ('drainage_characteristics', 'Drainage Characteristics'), ('temperature_humidity', 'Temperature & Humidity')], max_length=40)),
                ('characteristic', models.CharField(choices=[('alluvial', 'Alluvial'), ('forest_clayey', 'Forest/Clayey'), ('lateritic', 'Lateritic'), ('sandy', 'Sandy'), ('mangrove_forest', 'Mangrove Forest'), ('rain_forest', 'Rain Forest'), ('light_forest', 'Light Forest'), ('savannah', 'Savannah'), ('sahel_savannah', 'Sahel Savannah'), ('hill_top', 'Hill Top'), ('steeply_sloping_gt_20', 'Steeply Sloping (> 20 deg)'), ('moderately_sloping_10_to_20', 'Moderately Sloping (10 < x < 20 deg)'), ('mildly_sloping_lt_10', 'Mildly Sloping (x < 10 deg)'), ('flat', 'Flat'), ('valley', 'Valley'), ('subgrade_drainage', 'Subgrade Drainage'), ('vegetation_cover', 'Vegetation Cover'), ('topography', 'Topography'), ('rivers_streams', 'River and Streams'), ('very_hot_very_dry', 'Very Hot & Very Dry'), ('moderately_hot_dry', 'Moderately Hot & Dry'), ('moderately_hot_humid', 'Moderately Hot & Humid'), ('cool_dry', 'Cool & Dry')], max_length=40)),
                ('root_cause_analysis_text', models.TextField(blank=True)),
                ('root_cause_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_cause_details', to='all_roads.rootcauseanalysis')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
