# Generated by Django 4.0.5 on 2026-02-22 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0011_rootcauseanalysis_rootcausedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootcauseanalysis',
            name='description_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rootcauseanalysis',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('complete', 'Complete')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='rootcauseanalysis',
            name='supporting_file',
            field=models.FileField(blank=True, null=True, upload_to='root_cause/supporting/'),
        ),
        migrations.AlterField(
            model_name='rootcausedetail',
            name='root_cause_analysis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='root_cause_detail', to='all_roads.rootcauseanalysis'),
        ),
    ]
