# Generated by Django 4.0.5 on 2026-02-22 15:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def seed_defect_types_and_backfill_rca(apps, schema_editor):
    DefectType = apps.get_model("all_roads", "DefectType")
    RootCauseAnalysis = apps.get_model("all_roads", "RootCauseAnalysis")

    choices = [
        ("pavement", "Pavement"),
        ("shoulders", "Shoulders"),
        ("drainage", "Drainage"),
        ("traffic_volume", "Traffic Volume"),
        ("bridges", "Bridges"),
        ("culverts", "Culverts"),
        ("road_junctions", "Road Junctions"),
        ("others", "Others"),
    ]

    defect_lookup = {}
    for code, label in choices:
        defect_type, _ = DefectType.objects.get_or_create(
            code=code,
            defaults={"label": label, "is_active": True},
        )
        defect_lookup[code] = defect_type

    for analysis in RootCauseAnalysis.objects.all().iterator():
        selected_codes = analysis.description_options or []
        if not selected_codes and analysis.description:
            selected_codes = [analysis.description]
        valid_codes = [code for code in selected_codes if code in defect_lookup]
        if valid_codes:
            analysis.defect_types.set([defect_lookup[code] for code in valid_codes])


def unseed_defect_types(apps, schema_editor):
    DefectType = apps.get_model("all_roads", "DefectType")
    DefectType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0012_rootcauseanalysis_description_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('pavement', 'Pavement'), ('shoulders', 'Shoulders'), ('drainage', 'Drainage'), ('traffic_volume', 'Traffic Volume'), ('bridges', 'Bridges'), ('culverts', 'Culverts'), ('road_junctions', 'Road Junctions'), ('others', 'Others')], max_length=32, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('complete', 'Complete')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('defect_types', models.ManyToManyField(blank=True, related_name='physical_inspections', to='all_roads.defecttype')),
                ('subsegment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_inspections', to='all_roads.subsegment')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalInspectionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consideration_type', models.CharField(choices=[('design', 'Design Considerations'), ('construction', 'Construction Considerations'), ('usage', 'Usage Considerations')], max_length=24)),
                ('option', models.CharField(choices=[('horizontal_alignment', 'Horizontal Alignment'), ('vertical_alignment', 'Vertical Alignment'), ('carriage_way_cross_sections', 'Carriage Way Cross-Sections'), ('bridges', 'Bridges'), ('culverts', 'Culverts'), ('road_junction', 'Road Junction'), ('design_speed', 'Design Speed'), ('design_axle_load', 'Design Axle Load'), ('pavement_base_subbase_failure', 'Pavement, Base and Sub-base Failure'), ('drainage_construction_failure', 'Drainage Construction Failure'), ('pavement_failure', 'Pavement Failure'), ('drainage_failure', 'Drainage Failure'), ('encroachment', 'Encroachment')], max_length=64)),
                ('option_description', models.TextField(blank=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_rows', to='all_roads.physicalinspection')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalInspectionCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.CharField(max_length=64)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('row_index', models.PositiveSmallIntegerField(blank=True, help_text='For repeated carriage-way rows; keep between 1 and 8.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='all_roads.physicalinspectionanalysis')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalInspectionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='physical_inspection/supporting/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='all_roads.physicalinspection')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='rootcauseanalysis',
            name='defect_types',
            field=models.ManyToManyField(blank=True, related_name='root_cause_analyses', to='all_roads.defecttype'),
        ),
        migrations.AddConstraint(
            model_name='physicalinspectionanalysis',
            constraint=models.UniqueConstraint(fields=('inspection', 'option'), name='uq_physicalinspection_option'),
        ),
        migrations.RunPython(
            seed_defect_types_and_backfill_rca,
            reverse_code=unseed_defect_types,
        ),
    ]
