# Generated by Django 4.0.5 on 2026-02-24 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0015_alter_library_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_status', models.CharField(choices=[('draft_status', 'Draft status'), ('rca_status', 'RCA status'), ('physical_inspection_status', 'Physical Inspection status'), ('approved_status', 'Approved status'), ('repair_ongoing_status', 'Repair ongoing status'), ('repair_complete_status', 'Repair complete status')], default='draft_status', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('subsegment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='all_roads.subsegment')),
            ],
            options={
                'ordering': ['-modified', '-id'],
            },
        ),
        migrations.AddField(
            model_name='physicalinspection',
            name='defect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical_inspections', to='all_roads.defect'),
        ),
        migrations.AddField(
            model_name='rootcauseanalysis',
            name='defect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_cause_analyses', to='all_roads.defect'),
        ),
    ]
