# Generated by Django 4.0.5 on 2026-02-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0018_defect_engineer_defect_senior_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='condition',
            field=models.CharField(choices=[('no_response', 'No Response'), ('tolerable', 'Tolerable'), ('intolerable', 'Intolerable'), ('failed', 'Failed'), ('under_repair', 'Under Repair'), ('under_review', 'Under Review')], default='no_response', max_length=24),
        ),
    ]
