# Generated by Django 4.0.5 on 2026-02-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0019_defect_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='condition',
            field=models.CharField(choices=[('tolerable', 'Tolerable'), ('intolerable', 'Intolerable'), ('failed', 'Failed'), ('bad', 'Bad')], max_length=24),
        ),
        migrations.AlterField(
            model_name='defect',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('rca', 'RCA'), ('physical_inspection', 'Physical Inspection'), ('approved_status', 'Approved'), ('repair_ongoing', 'Repair ongoing'), ('repair_complete', 'Repair complete')], default='draft', max_length=32),
        ),
    ]
