# Generated by Django 4.0.5 on 2026-02-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0020_alter_defect_condition_alter_defect_workflow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('rca', 'RCA'), ('physical_inspection_draft', 'Physical Inspection Draft'), ('physical_inspection', 'Physical Inspection'), ('approved_status', 'Approved'), ('repair_ongoing', 'Repair ongoing'), ('repair_complete', 'Repair complete')], default='draft', max_length=32),
        ),
    ]
