# Generated by Django 4.0.5 on 2026-02-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0022_alter_defect_workflow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defect',
            name='closure_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='defect',
            name='defect_ref',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
