# Generated by Django 4.0.5 on 2026-02-24 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0023_defect_closed_at_defect_closure_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootcausedetail',
            name='root_cause_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_cause_details', to='all_roads.rootcauseanalysis'),
        ),
        migrations.AddConstraint(
            model_name='rootcausedetail',
            constraint=models.UniqueConstraint(fields=('root_cause_analysis', 'natural_feature'), name='uq_rootcausedetail_analysis_feature'),
        ),
    ]
