# Generated by Django 4.0.5 on 2026-02-24 21:05

from django.db import migrations, models
import django.db.models.deletion


def _infer_library_file_type(filename):
    name = (filename or "").lower()
    if name.endswith((".doc", ".docx", ".txt", ".rtf", ".odt")):
        return "document"
    if name.endswith((".xls", ".xlsx", ".ods")):
        return "spreadsheet"
    if name.endswith(".pdf"):
        return "pdf"
    if name.endswith(".csv"):
        return "csv"
    if name.endswith((".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp", ".svg")):
        return "image"
    if name.endswith((".ppt", ".pptx", ".odp")):
        return "presentation"
    if name.endswith((".geojson", ".json", ".kml", ".kmz", ".shp")):
        return "geo_data"
    return "other"


def copy_physical_attachments_to_library(apps, schema_editor):
    Library = apps.get_model("all_roads", "Library")
    PhysicalInspectionAttachment = apps.get_model("all_roads", "PhysicalInspectionAttachment")

    attachments = PhysicalInspectionAttachment.objects.select_related(
        "inspection",
        "inspection__defect",
    ).all()
    for item in attachments.iterator():
        inspection = getattr(item, "inspection", None)
        defect = getattr(inspection, "defect", None) if inspection else None
        file_name = (item.file.name or "").split("/")[-1] if item.file else ""
        created_item = Library.objects.create(
            entry_type="physical_inspection",
            file_type=_infer_library_file_type(file_name),
            name=file_name[:128] or "physical_attachment",
            file=item.file,
            defect=defect,
            physical_inspection=inspection,
        )
        if getattr(item, "uploaded_at", None):
            Library.objects.filter(pk=created_item.pk).update(
                created=item.uploaded_at,
                updated=item.uploaded_at,
            )


def reverse_copy_physical_attachments_to_library(apps, schema_editor):
    # Keep backfilled library records on reverse to avoid accidental file metadata loss.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0024_alter_rootcausedetail_root_cause_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='defect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_files', to='all_roads.defect'),
        ),
        migrations.AddField(
            model_name='library',
            name='physical_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_files', to='all_roads.physicalinspection'),
        ),
        migrations.AddField(
            model_name='library',
            name='root_cause_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_files', to='all_roads.rootcauseanalysis'),
        ),
        migrations.RunPython(
            copy_physical_attachments_to_library,
            reverse_copy_physical_attachments_to_library,
        ),
    ]
