# Generated by Django 4.0.5 on 2026-02-24 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0025_library_defect_library_physical_inspection_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhysicalInspectionAttachment',
        ),
    ]
