# Generated by Django 4.0.5 on 2026-02-24 21:09

from django.db import migrations


def _infer_library_file_type(filename):
    name = (filename or "").lower()
    if name.endswith((".doc", ".docx", ".txt", ".rtf", ".odt")):
        return "document"
    if name.endswith((".xls", ".xlsx", ".ods")):
        return "spreadsheet"
    if name.endswith(".pdf"):
        return "pdf"
    if name.endswith(".csv"):
        return "csv"
    if name.endswith((".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp", ".svg")):
        return "image"
    if name.endswith((".ppt", ".pptx", ".odp")):
        return "presentation"
    if name.endswith((".geojson", ".json", ".kml", ".kmz", ".shp")):
        return "geo_data"
    return "other"


def copy_rca_supporting_files_to_library(apps, schema_editor):
    RootCauseAnalysis = apps.get_model("all_roads", "RootCauseAnalysis")
    Library = apps.get_model("all_roads", "Library")
    qs = RootCauseAnalysis.objects.exclude(supporting_file="")
    for analysis in qs.iterator():
        if not analysis.supporting_file:
            continue
        file_name = (analysis.supporting_file.name or "").split("/")[-1]
        created_item = Library.objects.create(
            entry_type="root_cause_analysis",
            file_type=_infer_library_file_type(file_name),
            name=file_name[:128] or "root_cause_supporting_file",
            file=analysis.supporting_file,
            defect=analysis.defect,
            root_cause_analysis=analysis,
        )
        Library.objects.filter(pk=created_item.pk).update(
            created=analysis.created_at,
            updated=analysis.updated_at,
        )


def reverse_copy_rca_supporting_files_to_library(apps, schema_editor):
    # Keep copied library records on reverse to avoid data loss.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0026_delete_physicalinspectionattachment'),
    ]

    operations = [
        migrations.RunPython(
            copy_rca_supporting_files_to_library,
            reverse_copy_rca_supporting_files_to_library,
        ),
        migrations.RemoveField(
            model_name='rootcauseanalysis',
            name='supporting_file',
        ),
    ]
