# Generated by Django 4.0.5 on 2026-02-24 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('all_roads', '0027_remove_rootcauseanalysis_supporting_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_library_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
