# Generated by Django 4.0.5 on 2026-02-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0028_library_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('rca', 'RCA'), ('physical_inspection', 'Physical Inspection'), ('solution_design', 'Solution Design'), ('repair_ongoing', 'Repair ongoing'), ('repair_complete', 'Repair complete')], default='draft', max_length=32),
        ),
    ]
