# Generated by Django 4.0.5 on 2026-02-25 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import all_roads.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("all_roads", "0029_alter_defect_workflow_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defect",
            name="engineer",
            field=models.ForeignKey(
                blank=True,
                default=all_roads.models.get_default_amina_bello_user_id,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_defects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
