# Generated by Django 4.0.5 on 2026-02-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("all_roads", "0031_alter_defect_workflow_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="defect",
            name="review",
            field=models.BooleanField(default=False),
        ),
    ]
