# Generated by Django 4.0.5 on 2026-03-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0038_segment_length_db_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsegment',
            name='end_lat',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='subsegment',
            name='end_lon',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='subsegment',
            name='start_lat',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='subsegment',
            name='start_lon',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=18),
        ),
    ]
