# Generated by Django 4.0.5 on 2026-03-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0040_subsegment_segment_fk_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='status',
            field=models.CharField(choices=[('666699', 'No response'), ('F70202', 'Failed (<49 km/h)'), ('FF8D28', 'Intolerable (<59 km/h)'), ('2A6FDD', 'Tolerable (<69 km/h)'), ('1F8A70', 'Good (<79 km/h)')], default='666699', help_text='Traffic color code based on average speed', max_length=6),
        ),
        migrations.AlterField(
            model_name='subsegment',
            name='status',
            field=models.CharField(choices=[('666699', 'No response'), ('F70202', 'Failed (<49 km/h)'), ('FF8D28', 'Intolerable (<59 km/h)'), ('2A6FDD', 'Tolerable (<69 km/h)'), ('1F8A70', 'Good (<79 km/h)')], default='666699', help_text='Traffic color code based on average speed', max_length=6),
        ),
    ]
