# Generated by Django 5.2.13 on 2026-04-26 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_roads', '0060_assign_zone_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorabilitysetting',
            name='refresh_hour',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AlterField(
            model_name='motorabilitysetting',
            name='refresh_month_day',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
    ]
